# Generated by Django 5.1.7 on 2025-03-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.TextField(max_length=200)),
                ('blog_content', models.TextField()),
                ('blog_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
