# Generated by Django 5.1.7 on 2025-03-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('description', models.TextField()),
                ('highlights', models.CharField(blank=True, max_length=400, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
